### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Impulse-PW** [cossacklabs/0fc#8]
Everything went smoothly until I got to running the actual server.

I have pip3 and python 3.5.4 with all the needed dependencies. The console outputs this error:

```
`Traceback (most recent call last):
  File "server.py", line 28, in <module>
    from pythemis import ssession
  File "/usr/local/lib/python3.5/dist-packages/pythemis/ssession.py", line 60, in <module>
    ssession_create = themis.secure_session_create
  File "/usr/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python3: undefined symbol: secure_session_create`
```

I can't figure this one out, any help would be appreciated!

**Comment by mnaza** [comment]
Looks, like You did not install `themis` library, see https://github.com/cossacklabs/themis/wiki/Building-and-installing.

**Comment by Impulse-PW** [comment]
Would I be doing that as themis correct? I see it mentions pythemis in there as well. Installing the themis library rather than pythemis is giving me some errors as well, I'll have to get that resolved as well.

**Comment by gene-eu-zz** [comment]
First you need to build themis, which is system library, then install pythemis, is which python wrapper around it.

**Comment by Piero-Bird** [comment]
Requirement already satisfied: pythemis in /usr/local/lib/python3.5/dist-packages

I already have both things, I have no idea what's going on

**Comment by Impulse-PW** [comment]
I have both things, same error:

```
Traceback (most recent call last):
  File "server.py", line 28, in <module>
    from pythemis import ssession
  File "/usr/local/lib/python3.5/dist-packages/pythemis/ssession.py", line 60, in <module>
    ssession_create = themis.secure_session_create
  File "/usr/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python3: undefined symbol: secure_session_create
```

**Comment by mnaza** [comment]
`undefined symbol: secure_session_create` meen python not see `libthemis.so` library. Please check - by default it must be in /usr/lib. If `themis` Installed correctly try:
```
ldconfig
```
maybe you need `sudo` for that.

**Comment by Impulse-PW** [comment]
I checked and saw libthemis.so was there, I than ran "sudo ldconfig" before running "make install" again, everything seems to be working now!

Thank you

**Comment by Piero-Bird** [comment]
I don't know if this would be considered an issue so I'll ask here, any way I can allow guest connections? I don't know how to login lol
